inherit_from: .rubocop_todo.yml

# Что еще стоило бы добавить?
AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'spec/**/*.rb'
    - 'lib/**/*.rake'
  DisplayCopNames: true

# Стоит ли оставить это исключение?
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/LineLength:
  Max: 130

